# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    echo "Installing Package ..."
    npm install
    echo "Building Package ..."
    npm run build
  displayName: 'npm install and build'

- script: |
    echo "Installing standard-version package ..."
    npm install -g standard-version
    echo "Configuring git ..."
    git config --global user.email "azure@bot.com"
    git config --global user.name "Azurebot"
    echo "Bumping ..."
    standard-version
    git push --follow-tags origin HEAD:$(Build.SourceBranchName)
  condition: eq(variables['Build.SourceBranch'], 'refs/head/main')
  name: npm_bump_script
  displayName: 'Bump version'

# Release to GitHub
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'Token to GitHub'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    addChangeLog: true
